version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - 4c:f7:88:05:a7:9c:c6:82:87:35:92:07:3f:2d:7a:9d
      - checkout
      - run: sudo npm install
      - run: sudo npm install pug-cli -g
      - run: npm run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # Deploy docs from master or a tag
      - deploy:
          filters:
            branches:
              only: main
            tags:
              only: /^v.*/
